# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-04-08 15:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth2', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesstoken',
            name='scope',
            field=models.IntegerField(choices=[(2, 'read'), (4, 'write'), (6, 'read+write')], default=2),
        ),
        migrations.AlterField(
            model_name='client',
            name='client_type',
            field=models.IntegerField(choices=[(0, 'Confidential (Web applications)'), (1, 'Public (Native and JS applications)')]),
        ),
        migrations.AlterField(
            model_name='client',
            name='redirect_uri',
            field=models.URLField(help_text="Your application's callback URL"),
        ),
        migrations.AlterField(
            model_name='client',
            name='url',
            field=models.URLField(help_text="Your application's URL."),
        ),
    ]
